name: My Life in a Year With Twins
favicon: null
layout_spectrum: 0.972
typography_spectrum: 0.43085004412569106
title: 'How is to live with three loves: My wife, my daughter and my son.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#0b0c20'
    - '#7a7686'
    - '#145b14'
    - '#b93f21'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
