name: My Life in a Year With Twins
favicon: null
layout_spectrum: 0.02208
typography_spectrum: 0.43085004412569106
title: 'How is to live with three loves: My wife, my daughter and my son.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#a7d4e9'
    - '#3c3c3e'
    - '#737373'
    - '#979797'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
